ssh_authorized_keys:
- "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFsboQv73yrweDFHbr+zpF4dJbQk2Myh+l8Gvt+e5SXB4ujQeAVaBokrmu+EQGDpGWKNKWzCkkX6gvMXdyyE3CpVazjK2IKDvbZRxW1veODtzimnflSHdbamZeosCNh1xm0rasxfbMpuVWkjbBXomDs3m6nTtWlqI8buSsSq8c1GHNmIZZkz/YMP49UC56ReF/vs3W5jeoRCF86CbyUgf42aHlQg0Qh+wO9M0heBMM6UkBiAv9709173JP1tJvq4rKu4VknMbq57ULQPB2yUkH7X2JUZnslC5coI0G/JyiUW6wU56BQAK8H0BrfEDy4+FAHj7HJZ0JMwsJCmdnPDGANQn2DBNzGhTpiOBaNe80Uqd/DfhHj780vKsIdZXwYzeIclhqkCJoEXCdufyefyNd+GR07otbVSlW143MBPGzJuhTg4giKZkWTTz4Pu+4QXA3ZO+p+s/CNraa2Gix2tz5TWvW2GwDxfJJO9LOJQRpitqw0bM9wVABK/e87pdm+sc="
hostname: egb-m-k3s001.thuis.local

k3os:
  ntp_servers:
  - 0.eu.pool.ntp.org
  - 1.eu.pool.ntp.org
